### ISSUE TITLE
脆弱性を自動で修正するワークフローを作成する

### ISSUE THREAD

**Issue by nagashima-w** [nagashima-w/portal#54]
`.github/workflows/check-vulnerability-weekly.yml`のAcitonsで検知された脆弱性を自動で修正&PR作成してくれるActionsのワークフローを作成する

[こういうの](https://github.com/marketplace/actions/create-pull-request)と`npm audit fix`とかを組み合わせていい感じにしたい

**Comment by intercept6** [comment]
@nagashima-w 
自動で脆弱性対応やパッケージアップデートを行う為には前提として下記の対応のいずれかが完了している必要がある。

1. テストコードを書いて、変更後も正常に動作している事を担保できる
2. プルリクエスト作成時にテンポラリ環境を生成してマージするかの判断として実際にブラウザで動作確認できる

1の方が好ましいが、2でもOKです。また1はスナップショットテストのみでもOKです。
プルリクエストをレビューする際に、Pullしてローカルで動かすという運用も可能だけど十中八九面倒になってやらない。
